// Static + unit tests for the facilitator console (site/console).
//
// The console is a browser module, so the guarantees are asserted two ways: as source
// contracts (the shapes the deploy and the operator depend on) and as real unit tests on
// the pure guards that carry the money and card-custody invariants (ADR-0008/0013, ADR-0012).
import { assert, assertEquals, assertThrows } from "https://deno.land/std@0.224.0/assert/mod.ts";

const source = Deno.readTextFileSync("site/console/app.js");
const page = Deno.readTextFileSync("site/console/index.html");
const css = Deno.readTextFileSync("site/console/style.css");

// The module reads #app and wires a click listener at load time; give it a stub and tell it
// not to render, then import it for real so the guards under test are the shipped ones.
(globalThis as unknown as { document: unknown }).document = {
  querySelector: () => ({ addEventListener: () => {}, innerHTML: "" }),
};
(globalThis as unknown as { __CONSOLE_NO_AUTOSTART__: boolean }).__CONSOLE_NO_AUTOSTART__ = true;
const mod: any = await import("../site/console/app.js");

Deno.test("console route is a standalone shell with the four screens", () => {
  assert(page.includes('href="style.css"'));
  assert(page.includes('src="app.js"'));
  assert(page.includes("noindex"), "the money console is not for search engines");
  assertEquals(page.match(/<input|<form|<select/g), null, "the console document itself carries no input at all");
  assertEquals(mod.SCREENS, ["signin", "queue", "placing", "settlements"]);
  assert(css.includes(".shell.s1"), "the queue layout is styled");
});

Deno.test("sign-in is the server's NIP-98 challenge, signed on the device", () => {
  assert(source.includes("/auth/challenge"));
  assert(source.includes("kind: 27235"), "NIP-98 auth event");
  assert(source.includes('authorization: `Nostr '), "the signed challenge rides on every call");
  assert(source.includes("challenge.facilitatorNpub"));
  assert(source.includes("challenge.expiresIn"), "a stale challenge is not accepted");
  assert(source.includes('"method", "GET"'));
  assert(source.includes("never treats sign-in as a security boundary"), "the client does not pretend to verify");
});

Deno.test("CARD CUSTODY (ADR-0013): no card field, and card data is refused", () => {
  // No card field anywhere: not in the document, not generated by the script.
  assertEquals(page.match(/<(input|select|textarea|form)\b/gi), null, "the document holds no form field at all");
  assertEquals(page.match(/\b(name|id)\s*=\s*"[^"]*(card|pan|cvv|cvc|expir)/gi), null, "no card-shaped field name");
  assert(page.toLowerCase().includes("this console never") && page.includes("PAN/CVV"), "the custody rule is stated where the page is written");
  assert(!source.includes('type="password"'));
  assert(!source.includes("4242424242424242"), "no test PAN ships in production code");
  // The guard is real: keys, CVV-shaped values and Luhn-valid PANs are refused.
  assertThrows(() => mod.assertNoCardData({ pan: "x" }), mod.CardDataRefused);
  assertThrows(() => mod.assertNoCardData({ cvc: "123" }), mod.CardDataRefused);
  assertThrows(() => mod.assertNoCardData({ payment_reference: "4242 4242 4242 4242" }), mod.CardDataRefused);
  assertThrows(() => mod.assertNoCardData({ nested: { card_number: "4111111111111111" } }), mod.CardDataRefused);
  assertEquals(mod.looksLikePan("4242424242424242"), true);
  assertEquals(mod.looksLikePan("#4471"), false);
  assertEquals(mod.looksLikePan("pi_1AbC"), false);
  const ok = { venue_reference: "#4471", payment_reference: "pi_1AbC", paid_with: "card at the venue terminal" };
  assertEquals(mod.assertNoCardData(ok), ok);
  // The guard runs before every POST, before device storage, and before the Nostr bus.
  assert(source.includes('assertNoCardData({ state: to, ...extra }, `transition:${to}`)'));
  assert(source.includes('assertNoCardData(receipt, "device-receipt")'));
  assert(source.includes('assertNoCardData(escalationText(order, reason), "escalation-dm")'));
  const receiptWrite = source.indexOf('assertNoCardData(receipt, "device-receipt")');
  assert(receiptWrite > -1 && receiptWrite < source.indexOf("localStorage.setItem"), "the guard precedes the write");
});

Deno.test("card custody hands off instead of collecting", () => {
  const withUrl = mod.custodyPlan({ payload: { venue: { checkout_url: "https://venue.example/pay", rail: "FoodAmigos" } } });
  assertEquals(withUrl.mode, "venue-checkout");
  assertEquals(withUrl.url, "https://venue.example/pay");
  const without = mod.custodyPlan({ payload: {} });
  assertEquals(without.mode, "psp-hosted-fields");
  assertEquals(without.url, null);
  assert(without.note.toLowerCase().includes("card data never enters this console"));
  assert(source.includes('globalThis.open(plan.url, "_blank", "noopener,noreferrer")'), "hand-off is a real navigation, not a form");
});

Deno.test("ADR-0008/0013: no fiat spend without settled sats", () => {
  assertEquals(mod.requireSettled(undefined).ok, false);
  assertEquals(mod.requireSettled({ payload: {} }).ok, false);
  assertEquals(mod.requireSettled({ payload: { settlement: { status: "pending" } } }).ok, false);
  assertEquals(mod.requireSettled({ payload: { settlement: { status: "settled" } } }).ok, false, "settled without a payment id is not proof");
  assertEquals(mod.requireSettled({ payload: { settlement: { status: "settled", payment_hash: "abc", amount_sats: 0 } } }).ok, false);
  const settled = mod.requireSettled({ payload: { settlement: { status: "settled", payment_hash: "abc123", amount_sats: 27320, method: "bolt11" } } });
  assertEquals(settled.ok, true);
  assertEquals(settled.proof.amount_sats, 27320);
  assertEquals(settled.proof.payment_hash, "abc123");
  // Both fiat-spending paths are gated, and the gate is checked before anything opens.
  const blocked = source.split("fiat spend blocked").length - 1;
  assert(blocked >= 2, `placing and placed are both gated (found ${blocked})`);
  assert(source.indexOf("const gate = requireSettled(order);") < source.indexOf("await openHandoff(order);"));
  assert(source.includes('${gate.ok ? "" : "disabled"}'), "the place button is dead until the sats are proven");
  assert(source.includes('if (!receipt.venue_reference) throw new Error'), "a placed order without a venue reference is refused");
});

Deno.test("the console drives only the legal state machine", () => {
  assertEquals(mod.ORDER_MACHINE, { paid: ["placing", "refunded"], placing: ["placed", "refunded"], placed: ["ready"], ready: [], refunded: [] });
  assertEquals(mod.TRANSITIONS, ["paid", "placing", "placed", "ready", "refunded"]);
  assert(source.includes('api(`/orders/${encodeURIComponent(id)}/transition`'), "transitions go through the service, never through local state");
  assert(source.includes('method: "POST"'));
  assert(source.includes('await transition(orderId, "placing")'));
  assert(source.includes('await transition(orderId, "placed", { receipt })'));
  assert(source.includes('await transition(orderId, "ready")'));
  assert(source.includes('await transition(orderId, "refunded")'));
  assert(source.includes("allOrders()"), "orders we placed are re-read by id once they leave the paid queue");
});

Deno.test("ADR-0012: a terminal fiat failure escalates to the operator over Nostr DM", () => {
  assert(source.includes("ADR-0012"));
  assert(source.includes('kind: 4'), "an encrypted DM event");
  assert(source.includes('tags: [["p", recipient]]'));
  assert(source.includes("nip04"));
  assert(source.includes("fiat_cap_eur: 30"), "the escalation states the accepted loss cap");
  assert(source.includes("what_failed: reason"));
  assert(source.includes('await escalate(order, "facilitator could not place the order'));
  assert(source.includes("NOT SENT"), "an unsent escalation is shown, never swallowed");
  assert(source.includes('new Error("no operator pubkey to DM")'), "no recipient is a reported failure, not a silent one");
});

Deno.test("the console is fail-closed against a broken or lying service", () => {
  assert(source.includes("if (!res.ok) throw new Error("), "a non-2xx response is an error, not an empty success");
  assert(source.includes("auth challenge unavailable"));
  assert(source.includes("order service unavailable") || source.includes("failed (HTTP ${res.status})"));
  assert(source.includes('"captured on device"') && source.includes('"persisted server-side"'), "the receipt's durability is stated honestly");
  assert(source.includes("no NIP-07 signer on this device"), "a missing signer blocks sign-in instead of faking one");
  assertEquals(mod.RECEIPT_KEY, "cvm-console-receipts-v1");
  assertEquals(mod.SLA_MS, 5 * 60 * 1000);
});
